[env:esp32-s3-devkitc-1]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = fatfs
board_build.partitions = default_ffat_8MB.csv
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
build_type = debug

build_unflags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MSC_ON_BOOT=1
    -DARDUINO_USB_DFU_ON_BOOT=1
    -std=gnu++11

build_flags = 
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -std=gnu++17
