[platformio]
default_envs = esp32-s3-devkitc-1

[env]
build_flags = 
	-std=gnu++17                                                          ; necessary for using modern STL
	-Werror=return-type                                                   ; consider missing return information as fatal error
	-Werror=overflow
build_unflags = -std=gnu++11                                              ; necessary to be able to specify a different language standard

[production]
extends = env
lib_deps = 
	adafruit/Adafruit SSD1306@~2.5.3
	lvgl@^8.3
	johboh/nlohmann-json@^3.11.3
	3rd_party_adapters          ; this is necessary as no source code dependency shall exist to that packet
lib_ldf_mode = deep             ; to automatically detect nested dependencies (for external libraries)
build_flags = 
	${env.build_flags}
	-DLV_CONF_PATH="${PROJECT_DIR}/lib/3rd_party_adapters/LVGL/lv_conf.h" ; lvgl: use this config file
	-DBAUD_RATE=${this.monitor_speed}
board_build.filesystem = fatfs
monitor_speed = 115200
extra_scripts =
	pre:generate_vcs_identifier.py

[env:native]
platform = native
lib_deps =
	unity
	ArduinoFake@^0.4.0
	enterprise_business_rules
	utilities
lib_ldf_mode = chain ; to simplify mocking, do not use deep mode
build_flags =
	${env.build_flags}
	-Wno-deprecated ; Workaround for https://github.com/FabioBatSilva/ArduinoFake/pull/41#issuecomment-1440550553
	-lgcov
	--coverage
	-fprofile-abs-path
	-O0
	-ggdb3
	-Itest/doubles

[env:esp32-s3-devkitc-1]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
extends = production
board_build.partitions = default_ffat_8MB.csv
monitor_filters = esp32_exception_decoder
build_unflags =
	${production.build_unflags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MSC_ON_BOOT=1
    -DARDUINO_USB_DFU_ON_BOOT=1
build_flags = 
	${production.build_flags}
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
