[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = default_ffat_8MB.csv
board_build.filesystem = fatfs

lib_deps = 
    adafruit/Adafruit TinyUSB Library@3.3.4

monitor_filters = esp32_exception_decoder
