@startuml
title debouncing by post-event filtering: too short
caption too short pulse leads to wrong state
hide time-axis
scale 1 as 250 pixels
binary "digital input" as D
binary "debounced signal" as B

@0
D is low
note top of B : debounced
B is low
@+1
D is {low,high}
D@+0 <-> @+0.9 : bouncing
D -> B : rising edge detected
highlight +0 to +1 : state changes ignored
B is high
@+0.9
D is low
D -> B : state change ignored

@enduml
