name: Clang-Format Check

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  formatting-check:
    name: check style formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '17'
        fallback-style: 'none'

