name: PlatformIO CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install the project dependencies or custom packages
      run: platformio pkg install
    - name: Build default environment
      run: platformio run --verbose
    - name: Run tests on the native platform
      run: platformio test --verbose --environment test_native_hmi
